### PR TITLE
Delete .DS_Store

### PR DESCRIPTION
**Pull request by brandonapol**

### CODE REVIEW

**Review by JamesOrson — CHANGES_REQUESTED** [review]
Add a top-level `.gitignore` containing only an entry for `.DS_Store`

**Comment by brandonapol** [comment]
I did... will check to ensure that it worked tonight

**Comment by JamesOrson** [comment]
> I did... will check to ensure that it worked tonight

No I do not see a `.gitignore` at the top of the repo on your branch

**Comment by brandonapol** [comment]
oh you legit meant in this repo, I did another global one but OK will fix

**Review by brandonapol — COMMENTED** [review]
fixed lol

**Review by JamesOrson — APPROVED** [review]

**Pull request merged**
